### ISSUE TITLE
When using personalAccessToken, workspaceId should be optional, not required

### ISSUE THREAD

**Issue by seveibar** [seamapi/javascript-http#30]
![image](https://github.com/seamapi/javascript-http/assets/1910070/1508fda9-cf68-4238-866f-daa9ca8cfcdd)

**Comment by razor-x** [comment]
This is intentional for the `SeamHttp` client. To use endpoints that work without a workspace id, use the `SeamHttpMultiWorkspace`. Thanks for reporting this, since it make me realize the docs for `SeamHttpMultiWorkspace` never made it in. Fixed in https://github.com/seamapi/javascript-http/pull/32
