### ISSUE TITLE
Dynamically determine ignoredEndpointPaths

### ISSUE THREAD

**Issue by razor-x** [seamapi/javascript-http#72]
See https://github.com/seamapi/javascript-http/blob/21d77669ae8e53c9900731f4d54d6512e1defcf2/generate-routes.ts#L65-L74

The endpoints should either be removed from openapi spec, or openapi metadata should be added to exclude them.

**Comment by andrii-balitskyi** [comment]
`ignoredEndpointPaths` were excluded from the the openapi spec so no need to dynamically determine them.
